discussion_topics = [
    "Is technology making us more or less connected?",
    "Should social media platforms regulate content?",
    "Is climate change the most pressing issue of our time?",
    "Should genetically modified organisms be used in agriculture?",
    "Is space exploration important for humanity's future?",
    "Should the voting age be lowered or raised?",
    "Is universal  a viable solution to poverty?",
    "Should animals have the same rights as humans?",
    "Is it ethical to use animals for scientific experiments?",
    "Should the death penalty be abolished worldwide?"
  "Is freedom of speech essential for a democratic society?",
  "Should the government regulate the use of social media?",
  "Is climate change caused by human activity?",
  "Should genetically modified organisms be labeled in food products?",
  "Is space exploration a waste of resources?",
  "Should the voting age be standardized globally?",
  "Is universal healthcare a basic human right?",
  "Should all countries have mandatory military service?",
  "Is technology making us more isolated from each other?",
  "Should there be stricter regulations on gun ownership?",
  "Is online learning as effective as traditional classroom education?",
  "Should the legal driving age be raised?",
  "Is artificial intelligence a threat to jobs and employment?",
  "Should there be a limit on the number of children a family can have?",
  "Is privacy more important than national security?",
  "Should assisted suicide be legalized?",
  "Is the use of animal testing in scientific research ethical?",
  "Should the death penalty be implemented for heinous crimes?",
  "Is homeschooling beneficial for children's education?",
  "Should recreational drugs be legalized and regulated?",
  "Is capitalism the best economic system?",
  "Should there be term limits for political leaders?",
  "Is there a gender wage gap in the workplace?",
  "Should standardized testing be eliminated from education?",
  "Is cultural diversity important for social harmony?",
  "Should nuclear weapons be completely banned worldwide?",
  "Is renewable energy the future of the planet?",
  "Should there be a global ban on plastic bags?",
  "Is it ethical to eat meat and use animal products?",
  "Should there be mandatory national service for all citizens?",
  "Is there life beyond Earth?",
  "Should the legal age for alcohol consumption be lowered?",
  "Is globalization beneficial for developing countries?",
  "Should public transportation be free for everyone?",
  "Is human cloning morally acceptable?",
  "Should governments provide free healthcare for all citizens?",
  "Is cultural appropriation offensive?",
  "Should social media influencers be regulated?",
  "Is modern art valuable or overrated?",
  "Should the school day be shorter or longer?",
  "Is it ethical to use animals in entertainment, such as circuses?",
  "Should fast food advertising be banned?",
  "Is access to clean water a basic human right?",
  "Should there be a limit on executive salaries in corporations?",
  "Is surveillance necessary for public safety?",
  "Should there be a universal basic internet access?",
  "Is there a limit to freedom of artistic expression?",
  "Should prostitution be legalized and regulated?",
  "Is it ethical to keep animals in zoos?",
  "Should there be a global ban on single-use plastics?",
  "Is education the solution to reducing poverty?",
  "Should there be mandatory ethics education in schools?",
  "Is there a correlation between violent video games and real-life violence?",
  "Should the legal system focus more on rehabilitation than punishment?",
  "Is the concept of beauty subjective or objective?",
  "Should public schools teach religion?",
  "Is the use of body cameras by police officers effective?",
  "Should the government subsidize renewable energy sources?",
  "Is cultural assimilation harmful or beneficial?",
  "Should there be a limit on campaign spending for political candidates?",
  "Is it ethical to clone extinct animals to preserve biodiversity?",
  "Should there be a global ban on smoking in public places?",
  "Is artificial intelligence capable of having consciousness?",
  "Should there be a limit on the number of terms a politician can serve?",
  "Is there a link between mental health and creativity?",
  "Should there be stricter regulations on advertising to children?",
  "Is the use of nuclear energy a sustainable solution?",
  "Should there be a global tax on carbon emissions?",
  "Is social media causing mental health issues among young people?",
  "Should parents be held legally responsible for their children's actions?",
  "Is space colonization a realistic future for humanity?",
  "Should there be restrictions on the use of algorithms in decision-making?",
  "Is there a right to privacy in the digital age?",
  "Should art that is considered offensive be removed from public spaces?",
  "Is homeschooling a better alternative to traditional schooling?",
  "Should there be a limit on the size of corporate bonuses?",
  "Is technology making people lazier?",
  "Should the government regulate the production of genetically modified organisms?",
  "Is the use of animals in scientific research justified for medical advancement?",
  "Should there be stricter regulations on food additives and preservatives?",
  "Is there a need for stricter gun control laws?",
  "Should there be a global ban on animal testing for cosmetics?",
  "Is the concept of a nation-state becoming obsolete?",
  "Should there be limits on the consumption of meat to address climate change?",
  "Is there a need for a global language?",
  "Should public figures have a right to privacy?",
  "Is the concept of celebrity harmful to society?",
  "Should there be mandatory voting in democratic elections?",
  "Is there a limit to human population growth?",
  "Should there be restrictions on the use of facial recognition technology in public spaces?",
  "Is there a need for a global currency?",
  "Should the legal system prioritize rehabilitation over punishment for criminals?",
  "Is there a correlation between poverty and crime?",
  "Should there be a global ban on advertising unhealthy foods to children?",
  "Is the use of drones in warfare ethical?",
  "Should there be a universal basic healthcare system?",
  "Is the concept of time travel scientifically possible?",
  "Should the government invest more in space exploration?",
  "Is there a limit to economic growth?",
  "Should there be restrictions on the production and consumption of sugary beverages?",
  "Tell me about the best and worst parts of your day.",
  "What’s your favorite game to play?",
  "If you could be any animal what would you be and why?",
  "What’s your favorite thing to do in the car?",
  "If you could be anywhere right now where would you be? What would you be doing?",
  "What’s your favorite cereal? Why?",
  "What’s the silliest face that you can make?",
  "What’s your favorite song? Why do you like it?",
  "What was the best holiday you ever had?",
  "Where do you like to go in the car?",
  "If we were at the grocery store, what would you like to buy?",
  "How many animal noises can you make?",
  "Have you ever had an imaginary friend? Tell me about him.",
  "How high can you count?",
  "If you could make three wishes, what would they be?",
  "Who do you love? Why?",
  "What’s your favorite smell? What’s the yuckiest thing you’ve ever smelled?",
  "What’s your favorite weather? Why do you like that weather?",
  "When did you last say, “I do!”",
  "What’s the coolest thing you’ve ever built?",
  "When was the last time you were silly? What did you do?",
  "If you could be any pizza which one would you be?",
  "What do you want to be when you grow up?",
  "What would you do with a million dollars?",
  "What do you like most about Saturdays?",
  "What’s something that you don’t like?",
  "Tell me about your favorite movie or TV show.",
  "If you could only keep one toy which one would you keep? Why?",
  "If you could only keep one book which one would you keep? Why?",
  "What’s your favorite time of day? Why?",
  "What’s the best gift that you ever received? What made it special?",
  "What do you like the most about your family?",
  "What’s your favorite outfit? What do you like about it?",
  "What’s your favorite story?",
  "Have you ever lost something you really liked? What did you do?",
  "What’s the coolest thing you have ever seen?",
  "How many hugs do you need every day?",
  "What would you want to buy if money wasn’t an issue?",
  "What sound annoys you the most?",
  "What’s the longest walk you’ve ever taken?",
  "Name someone you trust. Why?",
  "What’s your favorite ice cream?",
  "What would you like to learn to do?",
  "What would you like to do more with your family?",
  "What color is the happiest color? What makes it happy?",
  "What do you enjoy doing with your family?",
  "What was the best party you ever went to? What made it fun?",
  "What’s one thing you forget to do regularly?",
  "What are the qualities that make a good friend?",
  "Do you think you should be paid for specific chores? Which ones? And how much do you think each is worth?",
  "What would you do if you had no TV?",
  "What do you do when you’re afraid?",
  "What’s your favorite food?",
  "If you could re-name yourself, what would you like to be called? Why?",
  "What’s your favorite color?",
  "Tell us a memory of something you did with your family.",
  "What’s the first thing that you remember about mom or dad (or a sibling)?",
  "What would you like me to play with you?",
  "How can we tell that you are happy? What do you do?",
  "What is one thing that you do not want to sell, for any price?",
  "What is the best surprise you ever had?",
  "What was your favorite thing of the summer?",
  "What was your favorite thing of the winter?",
  "What do you do when people stare at you?",
  "Do you pretend to be someone? Who? Why?",
  "Describe something silly that happened to someone else.",
  "What is the best thing that ever happened to you?",
  "What is your favorite candy?",
  "What is the funniest thing that ever happened to you?",
  "Tell us of a time that you were silly.",
  "What is the prettiest thing you have ever seen?",
  "If you were in a parade, who would you like to be?",
  "What would you like to collect?",
  "What are you thinking about right now?",
  "Who is the funniest person you know?",
  "What makes something or someone silly?",
  "What is your favorite room in the house? Why?",
  "What is the best gift you have ever given someone? What made it special?",
  "What is your favorite place in the house?",
  "If you could trade lives for one day with somebody you know, who would it be?",
  "Who is the meanest kid you know? Why?",
  "Do you think it's important to get physical education in school? Why or why not?",
  "If you could be any vegetable, what would you be?",
  "What was the nicest thing someone has ever done for you?",
  "What kids are popular in your grade? What do you think makes a person"
  "Is social media causing mental health issues among young people?",
  "Should there be restrictions on the use of algorithms in decision-making?",
  "Is there a right to privacy in the digital age?",
  "Should art that is considered offensive be removed from public spaces?",
  "Is homeschooling a better alternative to traditional schooling?",
  "Should there be a limit on the size of corporate bonuses?",
  "Is technology making people lazier?",
  "Should the government regulate the production of genetically modified organisms?",
  "Is the use of animals in scientific research justified for medical advancement?",
  "Should there be stricter regulations on food additives and preservatives?",
  "Is there a need for stricter gun control laws?",
  "Should there be a global ban on animal testing for cosmetics?",
  "Is the concept of a nation-state becoming obsolete?",
  "Should there be limits on the consumption of meat to address climate change?",
  "Is there a need for a global currency?",
  "Should public figures have a right to privacy?",
  "Is the concept of celebrity harmful to society?",
  "Should there be mandatory voting in democratic elections?",
  "Is there a limit to human population growth?",
  "Should there be restrictions on the use of facial recognition technology in public spaces?",
  "Is there a need for a global tax on carbon emissions?",
  "Is social media causing mental health issues among young people?",
  "Should parents be held legally responsible for their children's actions?",
  "Is space colonization a realistic future for humanity?",
  "Should there be restrictions on the use of algorithms in decision-making?",
  "Is there a right to privacy in the digital age?",
  "Should the legal system prioritize rehabilitation over punishment for criminals?",
  "Is there a correlation between poverty and crime?",
  "Should there be a global ban on advertising unhealthy foods to children?",
  "Is the use of drones in warfare ethical?",
  "Should there be a universal basic healthcare system?",
  "Is the concept of time travel scientifically possible?",
  "Should the government invest more in space exploration?",
  "Is there a limit to economic growth?",
  "Should there be restrictions on the production and consumption of sugary beverages?",
  "Tell me about the best and worst parts of your day.",
  "What’s your favorite game to play?",
  "If you could be any animal what would you be and why?",
  "What’s your favorite thing to do in the car?",
  "If you could be anywhere right now where would you be? What would you be doing?",
  "What’s your favorite cereal? Why?",
  "What’s the silliest face that you can make?",
  "What’s your favorite song? Why do you like it?",
  "What was the best holiday you ever had?",
  "Where do you like to go in the car?",
  "If we were at the grocery store, what would you like to buy?",
  "How many animal noises can you make?",
  "Have you ever had an imaginary friend? Tell me about him.",
  "How high can you count?",
  "If you could make three wishes, what would they be?"
]